feeds:
  - https://allinchamathjason.libsyn.com/rss  # All-In
  - https://thetwentyminutevc.libsyn.com/rss  # Twenty Minute VC
  - https://anchor.fm/s/7c624c84/podcast/rss  # This Week in Startups
  - https://api.substack.com/feed/podcast/10845.rss  # Lenny's Podcast
  - https://feeds.transistor.fm/acquired  # Acquired
  - https://feeds.simplecast.com/JGE3yC0V  # a16z Podcast
  - https://feeds.megaphone.fm/HS2300184645  # My First Million
  - https://feeds.megaphone.fm/YFL6537156961  # TechCrunch Equity
  - https://feeds.transistor.fm/the-indie-hackers-podcast  # Indie Hackers
  - https://saastr.libsyn.com/rss  # SaaStr Podcast
  - https://feeds.simplecast.com/3hnxp7yk  # Founders Podcast
  - https://anchor.fm/s/8c1524bc/podcast/rss  # Y Combinator Podcast
  - https://rss.art19.com/masters-of-scale  # Masters of Scale
  - https://feeds.npr.org/510313/podcast.xml  # How I Built This
  - https://feeds.megaphone.fm/thepitch  # The Pitch
  - https://feeds.castos.com/mqv6  # Startups for the Rest of Us
  - https://feeds.transistor.fm/bootstrapped-founder  # The Bootstrapped Founder
  - https://feeds.megaphone.fm/AHARO1075645324  # The SaaS Podcast
  - https://feeds.megaphone.fm/turpentinevc  # Turpentine VC
  - https://feeds.megaphone.fm/FS9665566819  # Fintech Insider
  - https://feeds.simplecast.com/4MvgQ73R  # UI Breakfast
  - https://feeds.megaphone.fm/hubermanlab  # Huberman Lab
  - https://feeds.npr.org/510051/podcast.xml  # Planet Money
  - https://feeds.buzzsprout.com/1889238.rss  # A Product Market Fit Show
download_path: data/audio
transcript_path: data/transcripts
model_size: base
