"harry": "Harry Stebbings"
"harry stabbings": "Harry Stebbings"
"jason calacanis": "Jason Calacanis"
"jcal": "Jason Calacanis"
"chamath": "Chamath Palihapitiya"
"david sacks": "David Sacks"
"sacks": "David Sacks"
"friedberg": "David Friedberg"
"elon": "Elon Musk"
"sbf": "Sam Bankman-Fried"
"Sam Bankman Fried": "Sam Bankman-Fried"
"Bankman-Fried": "Sam Bankman-Fried"
"Elon Musk.": "Elon Musk"
"Satya Nadella.": "Satya Nadella"
"sama": "Sam Altman"
"luke harry's": "Luke Harries"
"previously luke heldrolls": "__DELETE__"
"runner": "__DELETE__"
"luke": "Luke Harries"
"cliner perkins": "Kleiner Perkins"
"kleiner": "Kleiner Perkins"
"bat": "__DELETE__"

# Aliases for "Sovereign AI: Why Nations Are Building Their Own Models" episode
"anjane mita": "Anjney Midha"
"anjney mita": "Anjney Midha"
"guido": "Guido Appenzeller"
"appenzeller": "Guido Appenzeller"
"a16z": null